redis:
  addr: "127.0.0.1:6379"
  username: ""
  password: ""

influxdb:
  host: "127.0.0.1"
  port: 9086
  bucket: "tegenaria"
  org: "wetrycode"
  token: "9kCeULToVdZVdUGboG5qhiWaMiUUV1XKjKMlrFwPisNMKSENDAK3EBsuh_M-GFwGnNpQZkcZ6kPgltrDOHZo5g=="

log:
  path: "/var/logs/Tegenaria"
  level: "info" 